### PR TITLE
Add support for NeoVintageous search highlighting

### PR DESCRIPTION
**Pull request by gerardroche**
Re: https://github.com/NeoVintageous/NeoVintageous/issues/63#issuecomment-301948594

solarized-searches

### CODE REVIEW

**Comment by braver** [comment]
I've got a couple of questions and remarks about this:

- I have no real experience with Vim, Vintageous or NeoVintageuos. Can you tell me how to perform such a search so that I can check what it looks like myself?
- Relying on custom scopes is not very practical. You will not get the default color schemes to adapt these, and most other popular color schemes are not maintained actively. You don't want to have to point users of your package to a specific color scheme to enable all its features. 
- I don't think what you're introducing here should be handled by scopes anyway. Perhaps Sublime doesn't offer a really nice way to do this, but perhaps you could look at SublimeLinter and Color Highlighter for ideas on how to go about this without relying on color scheme implementations.

**Comment by gerardroche** [comment]
In NeoVintageous, with the following text in the view and `|` being the cursor position:

    |
    The Hitchhiker's Guide to the Gallaxy
    The Hitchhiker's Guide to the Gallaxy
    The Hitchhiker's Guide to the Gallaxy   

Make sure you are in normal mode, press Esc. 

Press slash `/` to begin a search pattern (`?` for reverse search), type the search pattern in the input box e.g. "The Hi". The first match will be highlighted. Press Enter and now all the occurences of the match will be highlighted. 

You can jump forward and backwards through the matches by pressing `n` for forward and `N` for backwards. Esc will clear the highlighting.

> Relying on custom scopes is not very practical. You will not get the default color schemes to adapt these, and most other popular color schemes are not maintained actively. You don't want to have to point users of your package to a specific color scheme to enable all its features.

This is why I prefixed the scope with "string" so that existing colour schemes will at least have basic support. I could have used a unique scope but sublime in that case would colour the highlights black/white. With string as the prefix existing colour schemes have basic support.

> I don't think what you're introducing here should be handled by scopes anyway. Perhaps Sublime doesn't offer a really nice way to do this, but perhaps you could look at SublimeLinter and Color Highlighter for ideas on how to go about this without relying on color scheme implementations

SublimeLinter actually does virtually the same as NeoVintageous. However, SublimeLinter provides defaults colours, but it does that by parsing your selected colour scheme to see if supports sublimelinter scopes, if it does then it does nothing, but if it doesn't then it copies your colour scheme, inserts the sublimelinter scopes with default colours, puts the modified colour scheme in `User/SublimeLinter/<original name> (SL).tmTheme`, and then sets preferences to use the modified theme. Other packages like Colour highlighter do the same thing. Try it. Enable one of the default colour schemes then check your preferences and you'll see that you're using a "User/SublimeLinter/* (SL).tmTheme" modified colour scheme.

I decided against the above in favour of just prefixing the scopes with "string" because it provides adequate support while also allowing popular themes to progressively enhance the feature with theme specific colours.

**Comment by braver** [comment]
Hm, I can't get the search to work, must be missing something. Whatever. I agree that there is not really nice solution for this. I think I would feel better about this if the scopes were explicitly linked to your package, but that would mean you would have to resort to antics like the linter and other packages to get some kind of highlighting happening.

Anyway, I made some tweaks and pushed c22cfc52d8409efb62f620917b912f224514df79 with support for this. @gerardroche  could you check if that works for you?

**Comment by gerardroche** [comment]
The colors you changed to are not good. Also setting only the background won't well because in some cases there won't be enough contrast between the foreground and background. 

The colours I used mirror those of [vim-solarized](https://github.com/altercation/vim-colors-solarized). One of the best things about Solarized is its consistency across platforms.

Here's what those colours look like in the dark theme:

solarized_search

solarized_search_occur

> Hm, I can't get the search to work, must be missing something

I assume you installed NeoVintageous via git and are on the master branch so it should be working fine.

When you open a file and put content in it like the screenshot all you should need to do to to search it press Escape to enter normal mode, then press forward slash `/` which should open an input box at the bottom of the screen like in the screenshot, then you type you search. In the screenshot the search is "the Ultimate". That will highlight the first match, then press enter to complete the search and it will highlight all the occurrences like in the second screenshot.

**Comment by braver** [comment]
> setting only the background won't well because in some cases there won't be enough contrast between the foreground and background

I prefer to maintain the original syntax highlighting if possible. I wasn't totally happy with the contrast in the dark version, I'll revise it later.

> The colours I used mirror those of vim-solarized. One of the best things about Solarized is its consistency across platforms.

That's a good basis, but Solarized is not very consistent across platforms at all. Pursuing such consistency would result in a lowest common denominator design, which is not what this specific implementation is about. We're trying to make Solarized for Sublime Text 3 the best it can be by utilising all the features available in this editor, and if this deviates from old implementations in Vim then so be it.

I don't know why NeoVintageous isn't working for me. However, the package isn't on package control yet and won't see much traction until it does. I'll revisit this when it's in package control.

**Pull request closed without merging**
